const cartTypes = {
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  INCREMENT_QUANTITY: "INCREMENT_QUANTITY",
  DECREMENT_QUANTITY: "DECREMENT_QUANTITY",
  CLEAN_UP_CART: "CLEAN_UP_CART",
  FETCH_CART_CONTENT_START: "FETCH_CART_CONTENT_START",
  FETCH_CART_CONTENT_SUCCESS: "FETCH_CART_CONTENT_SUCCESS",
  FETCH_CART_CONTENT_FAILURE: "FETCH_CART_CONTENT_FAILURE",
  INITIALIZE_CART_IN_DB_START: "INITIALIZE_CART_IN_DB_START",
  INITIALIZE_CART_IN_DB_SUCCESS: "INITIALIZE_CART_IN_DB_SUCCESS",
  INITIALIZE_CART_IN_DB_FAILURE: "INITIALIZE_CART_IN_DB_FAILURE",
  UPDATE_CART_IN_DB_START: "UPDATE_CART_IN_DB_START",
  UPDATE_CART_IN_DB_SUCCESS: "UPDATE_CART_IN_DB_SUCCESS",
  UPDATE_CART_IN_DB_FAILURE: "UPDATE_CART_IN_DB_FAILURE",
};

export default cartTypes;
