const cartTypes = {
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  INCREMENT_QUANTITY: "INCREMENT_QUANTITY",
  DECREMENT_QUANTITY: "DECREMENT_QUANTITY",
  FETCH_CART_CONTENT_START: "FETCH_CART_CONTENT_START",
  FETCH_CART_CONTENT_SUCCESS: "FETCH_CART_CONTENT_SUCCESS",
  FETCH_CART_CONTENT_FAILURE: "FETCH_CART_CONTENT_FAILURE",
};

export default cartTypes;
