const productsTypes = {
  FETCH_ALL_PRODUCTS_START: "FETCH_ALL_PRODUCTS_START",
  FETCH_ALL_PRODUCTS_SUCCESS: "FETCH_ALL_PRODUCTS_SUCCESS",
  FETCH_ALL_PRODUCTS_FAILURE: "FETCH_ALL_PRODUCTS_FAILURE",
  DELETE_ONE_PRODUCT_START: "DELETE_ONE_PRODUCT_START",
  DELETE_ONE_PRODUCT_SUCCESS: "DELETE_ONE_PRODUCT_SUCCESS",
  DELETE_ONE_PRODUCT_FAILURE: "DELETE_ONE_PRODUCT_FAILURE",
  UPDATE_ONE_PRODUCT_START: "UPDATE_ONE_PRODUCT_START",
  UPDATE_ONE_PRODUCT_SUCCESS: "UPDATE_ONE_PRODUCT_SUCCESS",
  UPDATE_ONE_PRODUCT_FAILURE: "UPDATE_ONE_PRODUCT_FAILURE",
  CREATE_ONE_PRODUCT_START: "CREATE_ONE_PRODUCT_START",
  CREATE_ONE_PRODUCT_SUCCESS: "CREATE_ONE_PRODUCT_SUCCESS",
  CREATE_ONE_PRODUCT_FAILURE: "CREATE_ONE_PRODUCT_FAILURE",
};

export default productsTypes;
