const productsTypes = {
  FETCH_ALL_PRODUCTS_START: "FETCH_ALL_PRODUCTS_START",
  FETCH_ALL_PRODUCTS_SUCCESS: "FETCH_ALL_PRODUCTS_SUCCESS",
  FETCH_ALL_PRODUCTS_FAILURE: "FETCH_ALL_PRODUCTS_FAILURE",
  DELETE_ONE_PRODUCT_START: "DELETE_ONE_PRODUCT_START",
  DELETE_ONE_PRODUCT_SUCCESS: "DELETE_ONE_PRODUCT_SUCCESS",
  DELETE_ONE_PRODUCT_FAILURE: "DELETE_ONE_PRODUCT_FAILURE",
  UPDATE_ONE_PRODUCT_START: "UPDATE_ONE_PRODUCT_START",
  UPDATE_ONE_PRODUCT_SUCCESS: "UPDATE_ONE_PRODUCT_SUCCESS",
  UPDATE_ONE_PRODUCT_FAILURE: "UPDATE_ONE_PRODUCT_FAILURE",
  LOAD_MORE_PRODUCTS: "LOAD_MORE_PRODUCTS",
  DELETE_ONE_PRODUCT: "DELETE_ONE_PRODUCT",
  UPDATE_ONE_PRODUCT: "UPDATE_ONE_PRODUCT",
};

export default productsTypes;
