const productsTypes = {
  FETCH_ALL_PRODUCTS_START: "FETCH_ALL_PRODUCTS_START",
  FETCH_ALL_PRODUCTS_SUCCESS: "FETCH_ALL_PRODUCTS_SUCCESS",
  FETCH_ALL_PRODUCTS_FAILURE: "FETCH_ALL_PRODUCTS_FAILURE",
  LOAD_MORE_PRODUCTS: "LOAD_MORE_PRODUCTS",
};

export default productsTypes;
