const authTypes = {
  FORM_SIGN_UP_START: "FORM_SIGN_UP_START",
  FORM_SIGN_UP_SUCCESS: "FORM_SIGN_UP_SUCCESS",
  FORM_SIGN_UP_FAILURE: "FORM_SIGN_UP_FAILURE",
  FORM_LOG_IN_START: "FORM_LOG_IN_START",
  FORM_LOG_IN_SUCCESS: "FORM_LOG_IN_SUCCESS",
  FORM_LOG_IN_FAILURE: "FORM_LOG_IN_FAILURE",
  LOG_OUT_START: "LOG_OUT_START",
  LOG_OUT_SUCCESS: "LOG_OUT_SUCCESS",
  LOG_OUT_FAILURE: "LOG_OUT_FAILURE",
  CHECK_USER_SESSION_START: "CHECK_USER_SESSION_START",
  CHECK_USER_SESSION_SUCCESS: "CHECK_USER_SESSION_SUCCESS",
  CHECK_USER_SESSION_FAILURE: "CHECK_USER_SESSION_FAILURE",
};

export default authTypes;
