const ordersTypes = {
  FETCH_ALL_ORDERS_START: "FETCH_ALL_ORDERS_START",
  FETCH_ALL_ORDERS_SUCCESS: "FETCH_ALL_ORDERS_SUCCESS",
  FETCH_ALL_ORDERS_FAILURE: "FETCH_ALL_ORDERS_FAILURE",
  CREATE_NEW_ORDER_START: "CREATE_NEW_ORDER_START",
  CREATE_NEW_ORDER_SUCCESS: "CREATE_NEW_ORDER_SUCCESS",
  CREATE_NEW_ORDER_FAILURE: "CREATE_NEW_ORDER_FAILURE",
};

export default ordersTypes;
